### ISSUE TITLE
Possible problem with binfmt registration

### ISSUE THREAD

**Issue by ismail** [infra-whizz/sys-mgr#6]
What I did

```
; sudo ./zypper-sysroot sysroot --create --name my_sysroot --arch aarch64
```

And tried to run a command afterwards:

```
; ls
Failed to execute process '/bin/ls'. Reason:
exec: unknown error (errno was 40)
```

Later debugging showed that every command was showing "Too many levels of symbolic links", this would happen when the loader is wrongly set up. But the problem is, binfmt code shouldn't have run for x86-64 but only for aarch64.

**Comment by isbm** [comment]
@ismail  https://github.com/infra-whizz/sys-mgr/pull/7

**Comment by isbm** [comment]
Resolved with the PR, mentioned above.
